config/routes.rb
Rails.application.routes.draw do
  # resources :employees
  #resources :employees
  root "employees#index"
  resources :employees, param: :emp_no do
    # post "query_data"
  end
  get 'query_page', to: 'employees#query_page'
  # get "employees/new/emp_no", to: 'employees#new', as: 'new_employee'
  # resources :employees, :except => [:new] 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bg_info.rb
class BgInfo < ApplicationRecord
    self.table_name = 'bg_info'
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/dept_emp.rb
class DeptEmp < ApplicationRecord
    self.table_name = 'dept_emp'
    belongs_to :employee, foreign_key: 'emp_no'
    belongs_to :department, foreign_key: 'dept_no'
end

app/models/dept_manager.rb
class DeptManager < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :salaries, foreign_key: 'emp_no'
 after_update :create_bg_info

    def create_bg_info
        BgInfo.create!(table_name: "Employee", table_id: emp_no)
    end
    
    def self.get_data
       Employee.select("YEAR(birth_date) AS year, COUNT(*) AS No_of_birth")
                      .group("year")
                      .order("No_of_birth DESC")
                      .limit(10)
    end
end

app/models/salary.rb
class Salary < ApplicationRecord
    belongs_to :employee
end

app/models/title.rb
class Title < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.first(10)
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  def query_page
    @hello = Employee.get_data
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:emp_no])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:emp_no, :birth_date, :first_name, :last_name, :gender, :hire_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Emp no:</strong>
    <%= employee.emp_no %>
  </p>

  <p>
    <strong>Birth date:</strong>
    <%= employee.birth_date %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= employee.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= employee.last_name %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= employee.gender %>
  </p>

  <p>
    <strong>Hire date:</strong>
    <%= employee.hire_date %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :emp_no, style: "display: block" %>
    <%= form.number_field :emp_no %>
  </div>

  <div>
    <%= form.label :birth_date, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :gender, style: "display: block" %>
    <%= form.text_field :gender %>
  </div>

  <div>
    <%= form.label :hire_date, style: "display: block" %>
    <%= form.date_field :hire_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>
<div>
  <%= link_to "query 1",  query_page_path %>
</div>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/query_page.html.erb
<table class= "table table-dark">
    <tr>
        <th>Year</th>
        <th>No_of_birth</th>
    </tr>
    <% @hello.each do |r| %>
        <tr>
            <td> <%= r.year %></td>
            <td> <%= r.No_of_birth %></td>
        </tr>
    <% end %>
</table>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>